- name: apt | config debconf-set-selections
  template:
    src: debconf-set-selections.j2
    dest: /tmp/debconf-set-selections.conf
  register: selections_status

- name: apt | run debconf-set-selections
  command: /usr/bin/debconf-set-selections /tmp/debconf-set-selections.conf
  when: selections_status|changed

- name: apt | add/remove package signing keys
  apt_key:
    url: "{{ item.key }}"
    state: "{{ item.state | default('present') }}"
  when: item.key is defined
  with_items: '{{ packages_repos }}'

- name: apt | add/remove package repos
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state | default('present') }}"
    update_cache: yes
  with_items: '{{ packages_repos }}'

- name: apt | update cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ packages_cache_valid_time | default(omit) }}"

- name: apt | remove packages
  apt:
    name: "{{ item }}"
    state: absent
  with_items: '{{ packages_remove }}'

- name: apt | add packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: '{{ packages_add }}'
